server:
  port: 8111

spring:
  application:
    name: FlyShare-Busi
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://${eureka.instance.hostname}:8000/eureka/
 
   