server:
  port: 8111

spring:
  application:
    name: flyshare-busi
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flyshare
    username: root
    password: 123456a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  
