server:
  port: 8080
  
spring:
  application:
    name: flyshare-ui
  thymeleaf:
    cache: false #开发环境不缓存
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5 #HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:53770/eureka/
      
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
