server:
  port: 8080
  
spring:
  application:
    name: flyshare-ui
  thymeleaf:
    cache: false #开发环境不缓存
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5 #HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:53770/eureka/
      
      