server:
  port: 8222
spring:
  application:
    name: flyshare-ui
  thymeleaf:
    cache: false #开发环境不缓存
    prefix: classpath:/templates/
    suffix: .html
    #mode: HTML5
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.web: INFO