server:
  port: 8500
  
spring:
  application:
    name: flyshare-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/dbjinjin0820/flyshare-config
          username: dbjinjin0820
          password: pz2008154954803

eureka:
  instance:
    appname: flyshare-config
  client:
    serviceUrl:
          defaultZone: http://root:123456@127.0.0.1:8000/eureka/          