server:
  port: 8500
  
spring:
  application:
    name: flyshare-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/dbjinjin0820/flyshare-config
          search-paths: snconfig
          username: dbjinjin0820
          password: pz2008154954803
  #rabbitmq:
    #host: 127.0.0.1
    #port: 5672
    #username: admin
    #password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
          defaultZone: http://root:123456@127.0.0.1:8000/eureka/
          
#management:
  #security:
    #enabled: false