spring:
  application:
    name: flyshare-eureka
   
server:
  port: 53770

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false #是否将自己注册到Eurek
    fetch-registry: false #是否从Eureka获取服务注册信息
    service-url:
       defaultZone: http://127.0.0.1:${server.port}/eureka/