spring:
  application:
    name: flyshare-eureka
  
server:
  port: 8001

eureka:
  server:
    enable-self-preservation: false #关闭自我保护模式     无效注册实例 及时删除
  instance:
    hostname: www.dbjinjin.com
  client:
    service-url:
       defaultZone: http://root:123456@www.ikcai.com:8002/eureka/

security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456