spring:
  application:
    name: flyshare-eureka
   
server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
       defaultZone: http://127.0.0.1:8001/eureka/