server:
  port: 8222
spring:
  application:
    name: flyshare-ui
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@www.dbjinjin.com:8001/eureka/,http://root:123456@www.ikcai.com:8002/eureka/
feign:
  hystrix:
    enabled: true #启用熔断器 (BUG 提示告警 配置无效)  